--liquibase formatted sql
--changeset makar:1

CREATE TABLE public.merchant_account (
       id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY ,
       "user_id" int8 NOT NULL UNIQUE ,
       "name" varchar(50) NOT NULL,
       "surname" varchar(50) NOT NULL,
       "patronymic" varchar(50),
       "INN" varchar(12) NOT NULL,
       "KPP" varchar(9) NOT NULL,
       "account_number" varchar(20) NOT NULL,
       "bank" varchar(50) NOT NULL,
       "BIK" varchar(9) NOT NULL,
       "activity_date" timestamp NOT NULL
);

--changeset makar:2
CREATE TABLE public.customer_account (
     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY ,
     "user_id" int8 NOT NULL UNIQUE,
     "activity_date" timestamp NOT NULL
);

--changeset makar:3
CREATE TABLE public.operation (
      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) PRIMARY KEY ,
      "account_id" int8 NOT NULL,
      "payment_id" varchar(50) NOT NULL UNIQUE ,
      "type" varchar(20) NOT NULL,
      "character" varchar(20) NOT NULL,
      "amount" int8 NOT NULL,
      "date" timestamp NOT NULL,
      "description" varchar(300) NOT NULL,
      foreign key (account_id) references customer_account (id)
);

