spring:
  application.name: "itmo-dws-se-2024"
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_SERVER_JWKS_URL:http://localhost:8099/realms/agregator/protocol/openid-connect/certs}
